// <auto-generated />
namespace Travel_Trek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populdatePerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populdatePerson));
        
        string IMigrationMetadata.Id
        {
            get { return "202105210020225_populdatePerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
